function JACSTRMAT = IPOPT_JACOBIAN_STRUCTURE(OCPINFO)

CNT_JACNL = size(OCPINFO.JACNLSTR,1);
JACSTRMAT = sparse( OCPINFO.JACNLSTR(:,1), ...
                    OCPINFO.JACNLSTR(:,2), ...
                    ones(CNT_JACNL,1), ...
                    OCPINFO.NNLPCON, ...
                    OCPINFO.NNLPVAR);
JACSTRMAT = spones(JACSTRMAT + spones(OCPINFO.JACLIMAT));