function HESSTRMAT = IPOPT_HESSIAN_STRUCTURE(OCPINFO)

CNT_HES     = size(OCPINFO.HESSTR,1);
HESSTRMAT   = sparse(   OCPINFO.HESSTR(:,1), ...
                        OCPINFO.HESSTR(:,2), ...
                        ones(CNT_HES,1), ...
                        OCPINFO.NNLPVAR, ...
                        OCPINFO.NNLPVAR);
HESSTRMAT   = spones(HESSTRMAT);