function FigPos = FIGURE_POSITION()

% position of figures

set(0,'Units','pixels')
scnsize     = get(0,'ScreenSize');
h0          = figure;
position    = get(h0,'Position');
outerpos    = get(h0,'OuterPosition');
borders     = outerpos - position;
close(h0)
edge        = -borders(1)/2;

FigPos.pos1 = [ edge,...
                scnsize(4) * (2/3),...
                scnsize(3)/4 - edge,...
                scnsize(4)/3 ];
FigPos.pos2 = [ edge,...
                scnsize(4) * (1/3),...
                scnsize(3)/4 - edge,...
                scnsize(4)/3 ];
FigPos.pos3 = [ edge + scnsize(3)/4,...
                scnsize(4) * (2/3),...
                scnsize(3)/4 - edge,...
                scnsize(4)/3 ];
FigPos.pos4 = [ edge + scnsize(3)/4,...
                scnsize(4) * (1/3),...
                scnsize(3)/4 - edge,...
                scnsize(4)/3 ];
FigPos.pos5 = [ edge + 2*scnsize(3)/4,...
                scnsize(4) * (2/3),...
                scnsize(3)/4 - edge,...
                scnsize(4)/3 ];
FigPos.pos6 = [ edge + 2*scnsize(3)/4,...
                scnsize(4) * (1/3),...
                scnsize(3)/4 - edge,...
                scnsize(4)/3 ];
FigPos.pos7 = [ edge + 3*scnsize(3)/4,...
                scnsize(4) * (2/3),...
                scnsize(3)/4 - edge,...
                scnsize(4)/3 ];
FigPos.pos8 = [ edge + 3*scnsize(3)/4,...
                scnsize(4) * (1/3),...
                scnsize(3)/4 - edge,...
                scnsize(4)/3 ];